// src/client/_scripts/impressum.tsx
import type { ParentProps } from 'solid-js';
import WaveTop from "./wave_top.tsx";

const Footer = (props: ParentProps) => (
  <footer class="text-center p-4" id="Impressum">{props.children}</footer>
);

const Div = (props: ParentProps) => (
  <div class="container justify-content-center d-flex align-items-center flex-column">{props.children}</div>
);

const ImpressumContent = () => (
  <>
    <h4>Impressum</h4>
    <p><strong>Förderverein des weiblichen Handballnachwuchses in Thüringen e.V.</strong></p>
    {/* <h5>Adresse</h5>
    <p class="m-0">c/o Steffen Ahrens</p>
    <p class="eingerückt m-0">Vor der Lohweide 29</p>
    <p class="eingerückt m-0">99092 Erfurt</p>
    <p class="eingerückt">Deutschland</p> */}
    <p class='m-0'>Ansprechpartner: Steffi Günther</p>
    <a href='tel:+4917644415740' class='mb-3'>Telefon: +49 176 44415740</a>
    <p>Email: info@whn-thueringen.de</p>
    <p>Vertreten durch: Ruben Arnold & Steffen Ahrens</p>
    <p>StNr.: 151/141/20933</p>
    <div class="line"></div>
    <a href="./datenschutz/">Datenschutzerklärung</a>
  </>
);


const Impressum = () => (
  <>
    <WaveTop></WaveTop>
    <Footer>
      <Div>
        <ImpressumContent></ImpressumContent>
      </Div>
    </Footer>
  </>
);

export default Impressum;

// src/lib/components/Impressum.svelte
<script>
  import WaveTop from "./WaveTop.svelte";
</script>

<WaveTop />

<footer class="text-center p-4" id="Impressum">
  <div class="container justify-content-center d-flex align-items-center flex-column">
    <h4>Impressum</h4>
    <p><strong>Förderverein des weiblichen Handballnachwuchses in Thüringen e.V.</strong></p>
    <p class='m-0'>Ansprechpartner: Steffi Günther</p>
    <p>Telefon: <a href='tel:+4917644415740' class='mb-3'>+49 176 44415740</a></p>
    <p>Email: <a href="mailto:info@whn-thueringen.de">info@whn-thueringen.de</a></p>
    <p>Vertreten durch: Ruben Arnold & Steffen Ahrens</p>
    <p>StNr.: 151/141/20933</p>
    <div class="line"></div>
    <a href="./datenschutz/">Datenschutzerklärung</a>
  </div>
</footer>
